### ISSUE TITLE
Re-enable clock advance assertion loop for OpenStudio external clock simulation test.

### ISSUE THREAD

**Issue by anyaelena** [NREL/alfalfa#308]

**Comment by TShapinsky** [comment]
I'm making some process on this. My best guess right now is that it has something with energyplus/bcvtb not properly terminating and causing issues on the socket

**Comment by TShapinsky** [comment]
After poking around in `ps aux` it is evident that mlep creates numerous orphaned processes which show up as `[runenergyplus] <defunct>`

**Comment by TShapinsky** [comment]
I think those initial thoughts were wrong. I think I have this fixed and will try to explain what was happening.

1. EnergyPlus sends a message to the external interface and waits for a response (the contents of the response are not important as long as it is in the right format) before continuing the timestep.
2. This means that when alfalfa starts communicating with e+ there is already a packet there waiting to be read.
3. However, alfalfa writes before it reads meaning that by the time it reads there are actually two packets in the buffer, one from the current timestep and one from the next.
4. At some point (this is the part I'm still not sure about) mlep drops one of the packets (possibly due to a buffer overflow).
5. This results in the packet queue decreasing in size from two packets to one. Which in turn looks like e+ jumped a step when it actually didn't.

**Comment by TShapinsky** [comment]
To fix this I am replacing the `exchange_data` call at the beginning of `advace_to_start_time` with a call that only reads the outputs from the packet. This should put alfalfa in sync with e+.

**Comment by anyaelena** [comment]
@TShapinsky Wow, great job tracking down and resolving this nasty bug!!
