### ISSUE TITLE
ERD for Postgres

### ISSUE THREAD

**Issue by anyaelena** [NREL/alfalfa#321]

**Comment by nllong** [comment]
I think this is all we need for the mongo replacement in Postgres. What do you think @TShapinsky.

<img width="651" alt="image" src="https://user-images.githubusercontent.com/1907354/180254539-39debd2d-6af8-4fec-8f60-13c776573b25.png">

Other questions/comments:
1. I prefer to use sqlalchemy and alembic for managing the db. This will give us the most flexibility in the future as migrations can be automatically generated. Thoughts?
2. Are we still storing senor readings in the database (through the Point model)?
3. Do we need a Simulation model? Seems like a run is a simulation? (I may be messing up our language.)
4. There will need to be quite a few iterations to make working with Postgres less painful. Mongo doesn't require authentication by default.
5. We'll need to setup environments with postgres (e.g., testing, dev, production, etc).

**Comment by TShapinsky** [comment]
1. That sounds good to me
2. I think we'll still need a point construct even if we move entirely to redis for read/write just to describe what the points are
3. It would probably be nice to have values other than doubles for doing equivalency checks with enumerations. (floating point numbers can sometimes fail equivalency checks, though not with whole numbers?)
4. I think a run replaces simulation. I think simulation possibly had some capacity for storing KPIs as an output of the run. I'm not sure if we're using this and if we were, simulation probably wouldn't be the right term anyways
5. I'm imagining the setup is probably done in the dispatcher or the run_manager using environment variables. We can also use sqlite for local testing
6. probably
7. I'd like to discus what the role of the site object is. As I see it isn't essentially just a haystack model. In which case maybe we should abstract it a bit more so that we can support Brick or ASHRAE 223 models in the future.

**Comment by nllong** [comment]
Toby suggests that we store some of the run statuses.

**Comment by anyaelena** [comment]
closing.  will revisit with #204
