### ISSUE TITLE
AHU Control via Haystack

### ISSUE THREAD

**Issue by madhu-kt** [NREL/alfalfa#34]
Hello,

I'm trying to use Alfalfa to set up a building simulation that can be controlled via a Haystack API (RTU heating/cooling stages, dampers, etc.). I can see routines in the workflow measures to create writable damper points but I'm unable to find one that converts RTU staging variables to the relevant Haystack conditioning points, e.g:
```
Conditioning
cool stage cmd
heat stage cmd
humidifier cmd
filter sensor
```
as shown [here](https://project-haystack.org/tag/ahu). 
Should the workflows be modified to support controlling of these variables? If so, what are the recommended steps to creating additional cmd points?

Thanks!

**Comment by corymosiman12** [comment]
Hey @MaDooSan - I would like to incorporate this as part of our [openstudio-alfalfa-gem](https://github.com/NREL/openstudio-alfalfa-gem) efforts.  @aviveiros11 and I have been planning that this gem will consist of some primary pieces:
1. Creating a better library for implementing Haystack tags on top of the OpenStudio SDK
1. Defining 'control profiles' for specific equipment type, wherein expected control points to be exposed as well as expected behavior when writing to those points (i.e. writing to `cool stage:1 cmd` should ....)
1. Implementation of the expected control profiles and tags via custom EMS modules (i.e. based on control profile 1 and system type = single stage cooling AHU, need to replace some components and add ems logic in this way...).

Will reach out offline to discuss.
